cars/urls.py
from django.urls import path, include
from . import views

app_name='cars_app'
urlpatterns = [
    path('cars/', views.Cars.as_view(), name="cars"),
]

carzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('cars.urls', namespace='cars')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path, include
from . import views

app_name='pages'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about', views.About.as_view(), name="about"),
    path('services', views.Services.as_view(), name="services"),
    path('contact', views.Contacts.as_view(), name="contacts"),
]

cars/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField
from multiselectfield import MultiSelectField

from django.forms import BooleanField, CharField, IntegerField

# Create your models here.
state_choice = (
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('DC', 'District Of Columbia'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    )

year_choice = []
for r in range(2000, (datetime.now().year+1)):
    year_choice.append((r,r))

features_choices = (
    ('Cruise Control', 'Cruise Control'),
    ('Audio Interface', 'Audio Interface'),
    ('Airbags', 'Airbags'),
    ('Air Conditioning', 'Air Conditioning'),
    ('Seat Heating', 'Seat Heating'),
    ('Alarm System', 'Alarm System'),
    ('ParkAssist', 'ParkAssist'),
    ('Power Steering', 'Power Steering'),
    ('Reversing Camera', 'Reversing Camera'),
    ('Direct Fuel Injection', 'Direct Fuel Injection'),
    ('Auto Start/Stop', 'Auto Start/Stop'),
    ('Wind Deflector', 'Wind Deflector'),
    ('Bluetooth Handset', 'Bluetooth Handset'),
)

door_choices = (
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)
class Car(models.Model):
    car_title=models.CharField(max_length=255)
    state = models.CharField(choices=state_choice, max_length=100)
    city = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField(('year'), choices=year_choice)
    condition = models.CharField(max_length=100)
    price = models.IntegerField()
    description = RichTextField()
    car_photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    car_photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    car_photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    car_photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    car_photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    features = MultiSelectField(choices=features_choices)
    body_style = models.CharField(max_length=100)
    engine = models.CharField(max_length=100)
    transmission = models.CharField(max_length=100)
    interior = models.CharField(max_length=100)
    miles = models.IntegerField()
    doors = models.CharField(choices=door_choices, max_length=10)
    passengers = models.IntegerField()
    vin_no = models.CharField(max_length=100)
    mileage = models.IntegerField()
    fuel_type = models.CharField(max_length=50)
    no_of_owners = models.CharField(max_length=100)
    is_featured = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=datetime.now,blank=True)
    
    def __str__(self):
        return self.car_title
    
    

pages/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    facebook_link = models.URLField(max_length=100)
    twitter_link = models.URLField(max_length=100)
    google_plus_link = models.URLField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.first_name

cars/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View, TemplateView

# Create your views here.
class Cars(TemplateView):
    template_name="cars/cars.html"

pages/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View, TemplateView
from . models import Team
from cars.models import Car

# Create your views here.
class Home(TemplateView):
    template_name="pages/home.html"
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['teams'] = Team.objects.all()
        context['featured_cars'] = Car.objects.order_by('-created_date').filter(is_featured=True)
        context['all_cars'] = Car.objects.all().order_by('-created_date')
        return context
    
class About(TemplateView):
    template_name="pages/about.html"
    def get_context_data(self, **kwargs):
        # Cal the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["teams"] = Team.objects.all()
        return context
        
    
class Services(TemplateView):
    template_name="pages/services.html"
    
class Contacts(TemplateView):
    template_name="pages/contact.html"
    

carzone/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <!-- External CSS libraries -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-submenu.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/linearicons/style.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'css/jquery.mCustomScrollbar.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'css/dropzone.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'css/lightbox.min.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'css/jnoty.css' %}">

    <!-- Custom stylesheet -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" id="style_sheet" href="{% static 'css/skins/red.css' %}">

    <!-- Favicon icon -->
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" >

    <!-- Google fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800%7CPlayfair+Display:400,700%7CRoboto:100,300,400,400i,500,700">



    <link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}">

    <script  src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
</head>
<body>
<div class="page_loader"></div>

{% include 'includes/topbar.html' %}
{% include 'includes/navbar.html' %}


{% block content %}



{% endblock content %}

<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="https://storage.googleapis.com/theme-vessel/carhouse/index.html#" class="search-header">
        <input type="search" value="" placeholder="type keyword(s) here. Eg: audi, benz etc" />
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>

{% include 'includes/footer.html' %}

<script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script  src="{% static 'js/bootstrap-submenu.js'%}"></script>
<script  src="{% static 'js/rangeslider.js' %}"></script>
<script  src="{% static 'js/jquery.mb.YTPlayer.js' %}"></script>
<script  src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script  src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script  src="{% static 'js/jquery.scrollUp.js'%}"></script>
<script  src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script  src="{% static 'js/dropzone.js' %}"></script>
<script  src="{% static 'js/slick.min.js' %}"></script>
<script  src="{% static 'js/jquery.filterizr.js' %}"></script>
<script  src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script  src="{% static 'js/jquery.countdown.js' %}"></script>
<script  src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
<script  src="{% static 'js/lightgallery-all.js' %}"></script>
<script  src="{% static 'js/jnoty.js' %}"></script>
<script  src="{% static 'js/app.js' %}"></script>

</body>
</html> 

carzone/templates/includes/footer.html
<!-- Footer start -->
<footer class="footer">
    
    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <p class="copy">© {% now "Y" %} Carzone Corp. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4">
                    <div class="social-list-2">
                        <ul>
                            <li><a href="https://facebook.com" target="_blank" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://twitter.com" target="_blank" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://google.com" target="_blank" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="https://linkedin.com" target="_blank" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer end -->

carzone/templates/includes/navbar.html
{% load static %}
<!-- Main header start -->
<header class="main-header sticky-header header-with-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand company-logo" href="{% url 'pages:home' %}">
                <img src="{% static 'img/logos/black-logo.png' %}" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a 
                        {% if '/' == request.path %}
                        class="nav-link active"
                        {% else %}
                        class="nav-link"
                        {% endif %}
                        href="{% url 'pages:home' %}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                        {% if 'cars' in request.path %}
                        class="nav-link active"
                        {% else %}
                        class="nav-link"
                        {% endif %}
                        href="{% url 'cars:cars' %}">
                            Cars
                        </a>
                    </li>
                    <li class="nav-item">
                        <a 
                        {% if 'about' in request.path %}
                        class="nav-link active"
                        {% else %}
                        class="nav-link"
                        {% endif %}
                        href="{% url 'pages:about' %}">
                            About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a 
                        {% if 'services' in request.path %}
                        class="nav-link active"
                        {% else %}
                        class="nav-link"
                        {% endif %}
                        href="{% url 'pages:services' %}">
                            Services
                        </a>
                    </li>
                    
                    
                    <li class="nav-item dropdown">
                        <a 
                        {% if 'contact' in request.path %}
                        class="nav-link active"
                        {% else %}
                        class="nav-link"
                        {% endif %}
                        href="{% url 'pages:contacts' %}">Contact</a>
                    </li>
                    <li class="nav-item dropdown m-hide">
                        <a href="#full-page-search" class="nav-link h-icon">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<!-- Main header end -->

carzone/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>About Us</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">About Us</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->
<!-- Service center strat -->
<div class="about-car content-area-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-6">
                <div class="about-car-photo">
                    <div id="carDetailsSlider" class="carousel car-details-sliders slide">
                        <!-- main slider carousel items -->
                        <div class="carousel-inner">
                            <div class="active item carousel-item" data-slide-number="0">
                                <img src="{% static 'img/car/car-1.jpg' %}" class="img-fluid" alt="slider-car">
                            </div>
                            <div class="item carousel-item" data-slide-number="1">
                                <img src="{% static 'img/car/car-2.jpg' %}" class="img-fluid" alt="slider-car">
                            </div>
                            <div class="item carousel-item" data-slide-number="2">
                                <img src="{% static 'img/car/car-3.jpg' %}" class="img-fluid" alt="slider-car">
                            </div>
                        </div>
                        <!-- main slider carousel nav controls -->
                        <ul class="carousel-indicators car-properties list-inline nav nav-justified">
                            <li class="list-inline-item active">
                                <a id="carousel-selector-0" class="selected" data-slide-to="0" data-target="#carDetailsSlider">
                                    <img src="{% static 'img/car/car-1.jpg' %}" class="img-fluid" alt="small-car">
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a id="carousel-selector-1" data-slide-to="1" data-target="#carDetailsSlider">
                                    <img src="{% static 'img/car/car-2.jpg' %}" class="img-fluid" alt="small-car">
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a id="carousel-selector-2" data-slide-to="2" data-target="#carDetailsSlider">
                                    <img src="{% static 'img/car/car-3.jpg' %}" class="img-fluid" alt="small-car">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xl-7 col-lg-6 align-self-center">
                <div class="best-used-car">
                    <h3>Welcome to <span>Car Zone</span></h3>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has</p>
                    <p class="mb-0">electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Service center end -->



<!-- Our team start -->
<div class="our-team content-area">
    <div class="container">
        <!-- Main title -->
        <div class="main-title">
            <h1>Executive <span>Team</span></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</p>
        </div>
        <!-- Slick slider area start -->
        <div class="slick-slider-area clearfix">
            <div class="row slick-carousel" data-slick='{"slidesToShow": 4, "responsive":[{"breakpoint": 1024,"settings":{"slidesToShow": 2}}, {"breakpoint": 768,"settings":{"slidesToShow": 1}}]}'>
                
                {% for team in teams %} 
                    <div class="slick-slide-item">
                        <div class="team-1">
                            <div class="photo">
                                <a href="#">
                                    <img src="{{ team.photo.url }}" alt="team-1" class="img-fluid">
                                </a>
                                <div class="social-list clearfix">
                                    <a href="{{team.facebook_link}}" target="_blank" class="facebook-bg"><i class="fa fa-facebook"></i></a>
                                    <a href="{{team.twitter_link}}" target="_blank" class="twitter-bg"><i class="fa fa-twitter"></i></a>
                                    <a href="{{team.google_plus_link}}" target="_blank" class="google-bg"><i class="fa fa-google"></i></a>
                                </div>
                            </div>
                            <div class="details">
                                <h4><a href="team-detail.html">{{ team.first_name }} {{ team.last_name }}</a></h4>
                                <h5>{{ team.designation }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Our team end -->

{% endblock content %}

carzone/templates/pages/cars.html
<h1>Cars</h1>

carzone/templates/pages/contact.html
{% extends 'base.html' %}

{% block content %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Contact Us</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">Contact Us</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- Contact 2 start -->
<div class="contact-2 content-area-5">
    <div class="container">
        <!-- Main title -->
        <div class="main-title text-center">
            <h1>Contact <span>Us</span></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</p>
        </div>
        <form action="#" method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-lg-7">
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <div class="form-group name">
                                <input type="text" name="name" class="form-control" placeholder="Full Name" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group email">
                                <input type="email" name="email" class="form-control" placeholder="Email" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group subject">
                                <input type="text" name="subject" class="form-control" placeholder="Subject" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group number">
                                <input type="text" name="phone" class="form-control" placeholder="Phone Number">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group message">
                                <textarea class="form-control" name="message" placeholder="Write message"></textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="send-btn text-center">
                                <button type="submit" class="btn btn-md button-theme">Send Message</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="contact-info-2">
                        <div class="ci-box">
                            <div class="icon">
                                <i class="flaticon-phone"></i>
                            </div>
                            <div class="detail">
                                <h5>Phone:</h5>
                                <p><a href="#">0477 8556 552</a></p>
                            </div>
                        </div>
                        <div class="ci-box">
                            <div class="icon">
                                <i class="flaticon-mail"></i>
                            </div>
                            <div class="detail">
                                <h5>Email:</h5>
                                <p><a href="#">info@themevessel.com</a></p>
                            </div>
                        </div>
                        <div class="ci-box">
                            <div class="icon">
                                <i class="flaticon-earth"></i>
                            </div>
                            <div class="detail">
                                <h5>Web:</h5>
                                <p><a href="#">info@themevessel.com</a></p>
                            </div>
                        </div>
                        <div class="ci-box mb-0">
                            <div class="icon">
                                <i class="flaticon-fax"></i>
                            </div>
                            <div class="detail">
                                <h5>Fax:</h5>
                                <p><a href="#">+0477 85X6 552</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Contact 2 end -->

{% endblock content %}

carzone/templates/pages/services.html
{% extends 'base.html' %}

{% block content %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Services</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">Services</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->
<!-- Services start -->
<div class="services content-area">
    <div class="container">
        <!-- Main title -->
        <div class="main-title text-center">
            <h1>Our <span>Services</span></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod</p>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">1</div>
                    <div class="icon">
                        <i class="flaticon-support-2"></i>
                    </div>
                    <div class="detail">
                        <h3>Free Support</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">2</div>
                    <div class="icon">
                        <i class="flaticon-speed"></i>
                    </div>
                    <div class="detail">
                        <h3>Super Fast</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">3</div>
                    <div class="icon">
                        <i class="flaticon-motor"></i>
                    </div>
                    <div class="detail">
                        <h3>Repairing</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">4</div>
                    <div class="icon">
                        <i class="flaticon-air-conditioner"></i>
                    </div>
                    <div class="detail">
                        <h3>AIR conditioning</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">5</div>
                    <div class="icon">
                        <i class="flaticon-fuel"></i>
                    </div>
                    <div class="detail">
                        <h3>Oil Change</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">7</div>
                    <div class="icon">
                        <i class="flaticon-wheel"></i>
                    </div>
                    <div class="detail">
                        <h3>Engine Repair</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">6</div>
                    <div class="icon">
                        <i class="flaticon-car-2"></i>
                    </div>
                    <div class="detail">
                        <h3>Dealership</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">8</div>
                    <div class="icon">
                        <i class="flaticon-lock"></i>
                    </div>
                    <div class="detail">
                        <h3>Security</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-info">
                    <div class="number">9</div>
                    <div class="icon">
                        <i class="flaticon-deal"></i>
                    </div>
                    <div class="detail">
                        <h3>Trusted Agents</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Services end -->

{% endblock content %}